using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client._NF.Shipyard.BUI;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared._NF.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects; // Lua
using Robust.Shared.Utility; // Lua
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using System.Numerics;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI;

public enum VesselSortType //DH
{
    Name,
    Price,
    Size,
    Class,
    Engine,
}

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!; // Lua

    public event Action<ButtonEventArgs>? OnSellShip;
    public event Action<ButtonEventArgs>? OnOrderApproved;
    public event Action<ButtonEventArgs>? OnUnassignDeed;
    public event Action<string>? OnRenameShip;
    public event Action<NetEntity?>? OnDockPortSelected; // Lua
    private readonly List<VesselSize> _categoryStrings = new();
    private readonly List<VesselClass> _classStrings = new();
    private readonly List<VesselEngine> _engineStrings = new();
    private readonly List<VesselSortType> _sortTypes = new(); //DH
    private VesselSize? _category;
    private VesselClass? _class;
    private VesselEngine? _engine;
    private VesselSortType? _sortBy = VesselSortType.Name; //DH

    private List<string> _lastAvailableProtos = new();
    private List<string> _lastUnavailableProtos = new();
    private bool _freeListings = false;
    private bool _validId = false;
    private bool _repopulatingFilters = false;
    private ConfirmButton? _currentlyConfirmingButton = null;

    // Lua start

    private NavInterfaceState? _dockNav;
    private NetEntity? _selectedDockPort;
    private readonly SharedTransformSystem _xform;
    private readonly SpriteSystem _sprite;

    private static readonly ResPath JobIcons = new("/Textures/Interface/Misc/job_icons.rsi");
    private static readonly ResPath NFJobIcons = new("/Textures/_NF/Interface/Misc/job_icons.rsi");
    private static readonly ResPath LuaJobIcons = new("/Textures/_Lua/Interface/Misc/job_icons.rsi");
    private static readonly ResPath LuaShuttleIcons = new("/Textures/_Lua/Interface/Misc/shuttle_icons.rsi");
    private static readonly ResPath ResearchDisciplines = new("/Textures/Interface/Misc/research_disciplines.rsi");

    private static readonly Dictionary<VesselClass, SpriteSpecifier.Rsi> VesselClassRsis = new()
    {
        [VesselClass.Nfsd] = new(NFJobIcons, "nfsdsergeant"),
        [VesselClass.LuaTech] = new(LuaJobIcons, "ops_luatech"),

        [VesselClass.Capital] = new(LuaShuttleIcons, "capital"),
        [VesselClass.Fighter] = new(LuaShuttleIcons, "fighter"),
        [VesselClass.Patrol] = new(LuaShuttleIcons, "patrol"),
        [VesselClass.Pursuit] = new(LuaShuttleIcons, "pursuit"),

        [VesselClass.Expedition] = new(JobIcons, "SecurityPilot"),
        [VesselClass.Scrapyard] = new(LuaShuttleIcons, "scrapyard"),

        [VesselClass.Salvage] = new(JobIcons, "ShaftMiner"),
        [VesselClass.Science] = new(ResearchDisciplines, "experimental"),
        [VesselClass.Cargo] = new(JobIcons, "CargoTechnician"),
        [VesselClass.Chemistry] = new(JobIcons, "Chemist"),
        [VesselClass.Botany] = new(JobIcons, "Botanist"),
        [VesselClass.Engineering] = new(JobIcons, "StationEngineer"),
        [VesselClass.Atmospherics] = new(JobIcons, "AtmosphericTechnician"),
        [VesselClass.Mercenary] = new(LuaJobIcons, "Mercenary"),
        [VesselClass.Medical] = new(JobIcons, "MedicalDoctor"),
        [VesselClass.Paramedical] = new(JobIcons, "Paramedic"),
        [VesselClass.Cryogenic] = new(LuaShuttleIcons, "cryogenic"),
        [VesselClass.Civilian] = new(ResearchDisciplines, "civilianservices"),
        [VesselClass.Kitchen] = new(JobIcons, "Chef"),

        [VesselClass.Syndicate] = new(JobIcons, "NoId"),
        [VesselClass.Pirate] = new(JobIcons, "NoId")
    };

    private static readonly SpriteSpecifier.Rsi VesselClassDefaultRsi = new(JobIcons, "NoId");

    private static readonly Dictionary<VesselEngine, EntProtoId> VesselEngineProtoIds = new()
    {
        [VesselEngine.AME] = "AmeJar",
        [VesselEngine.TEG] = "GeneratorRTG",
        [VesselEngine.Singularity] = "SingularityGenerator",
        [VesselEngine.Solar] = "SolarPanel",
        [VesselEngine.RTG] = "GeneratorRTG",
        [VesselEngine.APU] = "GeneratorWallmountAPU",
        [VesselEngine.Welding] = "PortableGeneratorJrPacmanShuttle",
        [VesselEngine.Plasma] = "FuelPlasma",
        [VesselEngine.Uranium] = "FuelUranium",
        [VesselEngine.Bananium] = "FuelBananium",
        [VesselEngine.Bluespace] = "FuelBluespace"
    };

    private static readonly EntProtoId VesselEngineDefaultProtoId = "MobCat";
    private const float PrimaryClassIconSize = 16f;
    private const float SecondaryClassIconSize = 12f;
    private const float PrimaryEngineIconSize = 28f;
    private const float SecondaryEngineIconSize = 21f;
    private const float IconSpacing = 2f;
    private const float SecondaryEngineIconSpacing = 3f;
    private static readonly Vector2 PrimaryEngineIconScale = new(2f, 2f);
    private static readonly Vector2 SecondaryEngineIconScale = new(1.5f, 1.5f);

    // Lua end

    public ShipyardConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xform = _entManager.System<SharedTransformSystem>(); // Lua
        _sprite = _entManager.System<SpriteSystem>(); // Lua
        Title = Loc.GetString("shipyard-console-menu-title");

        PopulateSortings(); //DH

        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        Categories.OnItemSelected += OnCategoryItemSelected;
        Classes.OnItemSelected += OnClassItemSelected;
        Sorting.OnItemSelected += OnSortingItemSelected; //DH
        Engines.OnItemSelected += OnEngineItemSelected;
        SellShipButton.OnPressed += (args) => { OnSellShip?.Invoke(args); };
        UnassignDeedButton.OnPressed += (args) => { OnUnassignDeed?.Invoke(args); };
        RenameButton.OnPressed += OnRenameButtonPressed;

        DockRadar.ShowIFF = false; // Lua
        DockRadar.ShowIFFShuttles = false; // Lua
        DockRadar.ShowDocks = true; // Lua
        DockRadar.OnRadarClick += OnDockRadarClick; // Lua
    }

    public void UpdateDockSelect(NavInterfaceState? nav, NetEntity? selectedPort) // Lua
    {
        if (nav == null)
        {
            _dockNav = null;
            _selectedDockPort = null;
            return;
        }
        _dockNav = nav;
        _selectedDockPort = selectedPort;
        DockRadar.UpdateState(nav);
        DockRadar.HighlightDockPort = selectedPort;
    }

    private void OnDockRadarClick(EntityCoordinates coords) // Lua
    {
        if (_dockNav == null) return;
        var clickMapPos = _xform.ToMapCoordinates(coords).Position;
        NetEntity? best = null;
        var bestDistSq = float.MaxValue;
        foreach (var (_, ports) in _dockNav.Docks)
        {
            foreach (var port in ports)
            {
                var portCoords = _entManager.GetCoordinates(port.Coordinates);
                if (!portCoords.IsValid(_entManager)) continue;
                var portMapPos = _xform.ToMapCoordinates(portCoords).Position;
                var distSq = (portMapPos - clickMapPos).LengthSquared();
                if (distSq < bestDistSq)
                {
                    bestDistSq = distSq;
                    best = port.Entity;
                }
            }
        }
        const float maxPickDistance = 4.0f; // Lua
        if (best == null || bestDistSq > maxPickDistance * maxPickDistance)
        {
            _selectedDockPort = null;
            DockRadar.HighlightDockPort = null;
            OnDockPortSelected?.Invoke(null);
            return;
        }
        if (_selectedDockPort.HasValue && best == _selectedDockPort.Value)
        {
            _selectedDockPort = null;
            DockRadar.HighlightDockPort = null;
            OnDockPortSelected?.Invoke(null);
            return;
        }
        _selectedDockPort = best;
        DockRadar.HighlightDockPort = best;
        OnDockPortSelected?.Invoke(best);
    }


    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_repopulatingFilters)
            return;

        SetCategoryText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnClassItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_repopulatingFilters)
            return;

        SetClassText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }
    //DH
    private void OnSortingItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_repopulatingFilters)
            return;

        SetSortingText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }
    //DH -

    private void OnEngineItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_repopulatingFilters)
            return;

        SetEngineText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnRenameButtonPressed(ButtonEventArgs args)
    {
        var newName = RenameLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(newName))
            return;

        // Validate length (30 characters max, matching ShuttleDeedComponent.MaxNameLength)
        if (newName.Length > 30)
        {
            newName = newName[..30];
        }

        OnRenameShip?.Invoke(newName);
        RenameLineEdit.Text = "";
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoryStrings[id];
        Categories.SelectId(id);
    }
    private void SetClassText(int id)
    {
        _class = id == 0 ? null : _classStrings[id];
        Classes.SelectId(id);
    }
    //DH
    private void SetSortingText(int id)
    {
        _sortBy = id >= 0 && id < _sortTypes.Count ? _sortTypes[id] : VesselSortType.Name;
        Sorting.SelectId(id);
    }

    private void SetEngineText(int id)
    {
        _engine = id == 0 ? null : _engineStrings[id];
        Engines.SelectId(id);
    }
    /// <summary>
    ///     Populates the list of products that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateProducts(List<string> availablePrototypes, List<string> unavailablePrototypes, bool free, bool canPurchase)
    {
        Vessels.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        var newVessels = FilterVessels(GetVesselPrototypesFromIds(availablePrototypes), search).ToList();
        var newUnavailableVessels = FilterVessels(GetVesselPrototypesFromIds(unavailablePrototypes), search).ToList();
        var visibleVessels = newVessels.Concat(newUnavailableVessels).ToList();
        var classColumnWidth = GetClassColumnWidth(visibleVessels);
        var engineColumnWidth = GetEngineColumnWidth(visibleVessels);

        AddVesselsToControls(newVessels, free, canPurchase, classColumnWidth, engineColumnWidth);
        AddVesselsToControls(newUnavailableVessels, free, false, classColumnWidth, engineColumnWidth);

        _lastAvailableProtos = availablePrototypes;
        _lastUnavailableProtos = unavailablePrototypes;
    }

    /// <summary>
    /// Given a set of prototype IDs, returns a corresponding set of prototypes, sorted based on _sortBy.
    /// </summary>
    private List<VesselPrototype?> GetVesselPrototypesFromIds(IEnumerable<string> protoIds)
    {
        var vesselList = protoIds.Select(it => _protoManager.TryIndex<VesselPrototype>(it, out var proto) ? proto : null)
            .Where(it => it != null)
            .ToList();

        //DH
        switch (_sortBy)
        {
            case VesselSortType.Price:
                vesselList.Sort((x, y) => x!.Price.CompareTo(y!.Price));
                break;
            case VesselSortType.Size:
                vesselList.Sort(CompareBySize);
                break;
            case VesselSortType.Class:
                vesselList.Sort(CompareBySelectedClass);
                break;
            case VesselSortType.Engine:
                vesselList.Sort(CompareBySelectedEngine);
                break;
            case VesselSortType.Name:
            default:
                vesselList.Sort((x, y) =>
                    string.Compare(x!.Name, y!.Name, StringComparison.CurrentCultureIgnoreCase));
                break;
        }

        return vesselList;
    }

    /// <summary>
    /// Adds all vessels in a given list of prototypes as VesselRows in the UI.
    /// </summary>
    private void AddVesselsToControls(
        IEnumerable<VesselPrototype> vessels,
        bool free,
        bool canPurchase,
        float classColumnWidth,
        float engineColumnWidth)
    {
        foreach (var prototype in vessels)
        {
            string priceText;
            if (free)
                priceText = Loc.GetString("shipyard-console-menu-listing-free");
            else
                priceText = BankSystemExtensions.ToSpesoString(prototype.Price); // Lua

            var vesselEntry = new VesselRow
            {
                Vessel = prototype,
                // Lua start
                VesselName = { Text = prototype.Name },
                CategoryLabel = { Text = Loc.GetString($"shipyard-console-category-{prototype.Category}") },
                // Lua end
                Purchase = { Text = Loc.GetString("shipyard-console-purchase-available"), Disabled = !canPurchase },
                Guidebook = { Disabled = prototype.GuidebookPage is null, TooltipDelay = 0.2f, ToolTip = prototype.Description },
                Price = { Text = priceText },
            };
            vesselEntry.ClassIcons.MinWidth = classColumnWidth;
            vesselEntry.ClassIcons.MaxWidth = classColumnWidth;
            vesselEntry.EngineIcons.MinWidth = engineColumnWidth;
            vesselEntry.EngineIcons.MaxWidth = engineColumnWidth;
            PopulateClassIcons(vesselEntry, prototype);
            PopulateEngineIcons(vesselEntry, prototype);
            vesselEntry.Purchase.OnConfirming += OnStartConfirmingPurchase;
            vesselEntry.Purchase.OnPressed += (args) => { _currentlyConfirmingButton = null; OnOrderApproved?.Invoke(args); };
            Vessels.AddChild(vesselEntry);
        }
    }

    /// <summary>
    /// Confirming handler: ensures that only one button is confirming at a time.
    /// </summary>
    private void OnStartConfirmingPurchase(ButtonEventArgs args)
    {
        if (args.Button is not ConfirmButton confirmButton)
            return;

        if (_currentlyConfirmingButton != null)
            _currentlyConfirmingButton.ClearIsConfirming();
        _currentlyConfirmingButton = confirmButton;
    }

    /// <summary>
    ///     Populates the list categories that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateCategories(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        var previousCategory = _category;
        _repopulatingFilters = true;

        _categoryStrings.Clear();
        Categories.Clear();

        AddCategoriesFromPrototypes(availablePrototypes);
        AddCategoriesFromPrototypes(unavailablePrototypes);

        _categoryStrings.Sort();

        // Add "All" category at the top of the list
        _categoryStrings.Insert(0, VesselSize.All);

        foreach (var str in _categoryStrings)
        {
            Categories.AddItem(Loc.GetString($"shipyard-console-category-{str}"));
        }

        RestoreCategorySelection(previousCategory);
        _repopulatingFilters = false;
    }

    /// <summary>
    /// Adds all ship categories from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddCategoriesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            if (!_categoryStrings.Contains(prototype.Category) && prototype.Category != VesselSize.All)
            {
                _categoryStrings.Add(prototype.Category);
            }
        }
    }

    /// <summary>
    ///     Populates the list classes that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateClasses(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        var previousClass = _class;
        _repopulatingFilters = true;

        _classStrings.Clear();
        Classes.Clear();

        AddClassesFromPrototypes(availablePrototypes);
        AddClassesFromPrototypes(unavailablePrototypes);

        _classStrings.Sort();

        // Add "All" category at the top of the list
        _classStrings.Insert(0, VesselClass.All);

        foreach (var str in _classStrings)
        {
            Classes.AddItem(Loc.GetString($"shipyard-console-class-{str}"));
        }

        RestoreClassSelection(previousClass);
        _repopulatingFilters = false;
    }

    /// <summary>
    /// Adds all ship classes from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddClassesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Classes)
            {
                if (!_classStrings.Contains(cl) && cl != VesselClass.All)
                {
                    _classStrings.Add(cl);
                }
            }
        }
    }

    /// <summary>
    ///     Populates the list engines that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateEngines(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        var previousEngine = _engine;
        _repopulatingFilters = true;

        _engineStrings.Clear();
        Engines.Clear();

        AddEnginesFromPrototypes(availablePrototypes);
        AddEnginesFromPrototypes(unavailablePrototypes);

        _engineStrings.Sort();

        // Add "All" category at the top of the list
        _engineStrings.Insert(0, VesselEngine.All);

        foreach (var str in _engineStrings)
        {
            Engines.AddItem(Loc.GetString($"shipyard-console-engine-{str}"));
        }

        RestoreEngineSelection(previousEngine);
        _repopulatingFilters = false;
    }

    /// <summary>
    /// Adds all ship engine power type from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddEnginesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Engines)
            {
                if (!_engineStrings.Contains(cl) && cl != VesselEngine.All)
                {
                    _engineStrings.Add(cl);
                }
            }
        }
    }
    /// <summary>
    ///     Populates the list of sorting options that will be shown.
    ///     Uses localization keys like shipyard-console-sorting-all-label and shipyard-console-sorting-price-label.
    /// </summary>
    public void PopulateSortings()
    {
        var previousSorting = _sortBy;
        _repopulatingFilters = true;

        _sortTypes.Clear();
        Sorting.Clear();

        _sortTypes.Add(VesselSortType.Name);
        _sortTypes.Add(VesselSortType.Price);
        _sortTypes.Add(VesselSortType.Size);
        _sortTypes.Add(VesselSortType.Class);
        _sortTypes.Add(VesselSortType.Engine);

        Sorting.AddItem(Loc.GetString("shipyard-console-sorting-all-label"));
        Sorting.AddItem(Loc.GetString("shipyard-console-sorting-price-label"));
        Sorting.AddItem(Loc.GetString("shipyard-console-sorting-size-label"));
        Sorting.AddItem(Loc.GetString("shipyard-console-sorting-class-label"));
        Sorting.AddItem(Loc.GetString("shipyard-console-sorting-engine-label"));

        RestoreSortingSelection(previousSorting);
        _repopulatingFilters = false;
    }

    private void RestoreCategorySelection(VesselSize? previousCategory)
    {
        var id = previousCategory == null ? 0 : _categoryStrings.IndexOf(previousCategory.Value);
        SetCategoryText(id < 0 ? 0 : id);
    }

    private void RestoreClassSelection(VesselClass? previousClass)
    {
        var id = previousClass == null ? 0 : _classStrings.IndexOf(previousClass.Value);
        SetClassText(id < 0 ? 0 : id);
    }

    private void RestoreEngineSelection(VesselEngine? previousEngine)
    {
        var id = previousEngine == null ? 0 : _engineStrings.IndexOf(previousEngine.Value);
        SetEngineText(id < 0 ? 0 : id);
    }

    private void RestoreSortingSelection(VesselSortType? previousSorting)
    {
        var id = previousSorting == null ? 0 : _sortTypes.IndexOf(previousSorting.Value);
        SetSortingText(id < 0 ? 0 : id);
    }

    private int CompareBySize(VesselPrototype? x, VesselPrototype? y)
    {
        var sizeComparison = x!.Category.CompareTo(y!.Category);
        if (sizeComparison != 0)
            return sizeComparison;

        return CompareByName(x, y);
    }

    private int CompareBySelectedClass(VesselPrototype? x, VesselPrototype? y)
    {
        var rankComparison = GetSelectedClassRank(x).CompareTo(GetSelectedClassRank(y));
        if (rankComparison != 0)
            return rankComparison;

        return CompareByName(x, y);
    }

    private int CompareBySelectedEngine(VesselPrototype? x, VesselPrototype? y)
    {
        var rankComparison = GetSelectedEngineRank(x).CompareTo(GetSelectedEngineRank(y));
        if (rankComparison != 0)
            return rankComparison;

        return CompareByName(x, y);
    }

    private int GetSelectedClassRank(VesselPrototype? vessel)
    {
        if (vessel == null || _class == null)
            return 0;

        var index = vessel.Classes.IndexOf(_class.Value);
        return index < 0 ? int.MaxValue : index;
    }

    private int GetSelectedEngineRank(VesselPrototype? vessel)
    {
        if (vessel == null || _engine == null)
            return 0;

        var index = vessel.Engines.IndexOf(_engine.Value);
        return index < 0 ? int.MaxValue : index;
    }

    private static int CompareByName(VesselPrototype? x, VesselPrototype? y)
    {
        return string.Compare(x!.Name, y!.Name, StringComparison.CurrentCultureIgnoreCase);
    }

    private IEnumerable<VesselPrototype> FilterVessels(IEnumerable<VesselPrototype?> vessels, string search)
    {
        foreach (var prototype in vessels)
        {
            if (prototype == null)
                continue;

            if (_category != null && !prototype.Category.Equals(_category))
                continue;
            if (_class != null && !prototype.Classes.Contains(_class.Value))
                continue;
            if (_engine != null && !prototype.Engines.Contains(_engine.Value))
                continue;
            if (search.Length > 0 && !prototype.Name.ToLowerInvariant().Contains(search))
                continue;

            yield return prototype;
        }
    }

    private static float GetClassColumnWidth(IEnumerable<VesselPrototype> vessels)
    {
        var maxCount = Math.Max(1, vessels.Select(vessel => vessel.Classes.Count).DefaultIfEmpty(1).Max());
        return PrimaryClassIconSize + IconSpacing + (maxCount - 1) * (SecondaryClassIconSize + IconSpacing);
    }

    private static float GetEngineColumnWidth(IEnumerable<VesselPrototype> vessels)
    {
        var maxCount = Math.Max(1, vessels.Select(vessel => vessel.Engines.Count).DefaultIfEmpty(1).Max());
        return PrimaryEngineIconSize + IconSpacing + (maxCount - 1) * (SecondaryEngineIconSize + SecondaryEngineIconSpacing);
    }

    private void PopulateClassIcons(VesselRow vesselEntry, VesselPrototype prototype)
    {
        vesselEntry.ClassIcons.RemoveAllChildren();

        if (prototype.Classes.Count == 0)
        {
            AddClassIcon(vesselEntry, VesselClassDefaultRsi, false);
            return;
        }

        for (var i = 0; i < prototype.Classes.Count; i++)
        {
            var classRsi = VesselClassRsis.GetValueOrDefault(prototype.Classes[i], VesselClassDefaultRsi);
            AddClassIcon(vesselEntry, classRsi, i > 0);
        }
    }

    private void AddClassIcon(VesselRow vesselEntry, SpriteSpecifier.Rsi classRsi, bool secondary)
    {
        var iconSize = secondary ? SecondaryClassIconSize : PrimaryClassIconSize;
        vesselEntry.ClassIcons.AddChild(new TextureRect
        {
            Texture = _sprite.GetState(classRsi).Frame0,
            SetSize = new Vector2(iconSize, iconSize),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Margin = new Thickness(secondary ? 1 : 0, 0, 1, 0),
        });
    }

    private void PopulateEngineIcons(VesselRow vesselEntry, VesselPrototype prototype)
    {
        vesselEntry.EngineIcons.RemoveAllChildren();

        if (prototype.Engines.Count == 0)
        {
            AddEngineIcon(vesselEntry, VesselEngineDefaultProtoId, false);
            return;
        }

        for (var i = 0; i < prototype.Engines.Count; i++)
        {
            var engineProtoId = VesselEngineProtoIds.GetValueOrDefault(prototype.Engines[i], VesselEngineDefaultProtoId);
            AddEngineIcon(vesselEntry, engineProtoId, i > 0);
        }
    }

    private void AddEngineIcon(VesselRow vesselEntry, EntProtoId engineProtoId, bool secondary)
    {
        var iconSize = secondary ? SecondaryEngineIconSize : PrimaryEngineIconSize;
        vesselEntry.EngineIcons.AddChild(new TextureRect
        {
            Texture = _sprite.Frame0(_protoManager.Index(engineProtoId)),
            SetSize = new Vector2(iconSize, iconSize),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            TextureScale = secondary ? SecondaryEngineIconScale : PrimaryEngineIconScale,
            Margin = new Thickness(secondary ? 1 : 0, 0, 2, 0),
        });
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        var shipPrice = 0;
        if (!state.FreeListings)
            shipPrice = state.ShipSellValue;

        ShipAppraisalLabel.Text = $"{BankSystemExtensions.ToSpesoString(shipPrice)} ({state.SellRate * 100.0f:F1}%)";
        SellShipButton.Disabled = state.ShipDeedTitle == null;
        UnassignDeedButton.Disabled = state.ShipDeedTitle == null;

        // Show/hide and enable/disable rename controls based on whether there's a ship deed
        var hasShipDeed = state.ShipDeedTitle != null;
        RenameContainer.Visible = hasShipDeed;
        RenameLineEdit.Editable = hasShipDeed;
        RenameButton.Disabled = !hasShipDeed;

        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        NoDeedHelperContainer.Visible = !state.IsTargetIdPresent;
        //DeedContainer.Visible = state.IsTargetIdPresent; // Lua
        if (state.ShipDeedTitle != null)
        {
            DeedTitle.Text = state.ShipDeedTitle;
        }
        else
        {
            DeedTitle.Text = Loc.GetString($"shipyard-console-deed-label-none");
        }
        _freeListings = state.FreeListings;
        _validId = state.IsTargetIdPresent;
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }
}
