using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.Interserver;

[GenerateTypedNameReferences]
public sealed partial class InterserverRedialWindow : DefaultWindow
{
    [Dependency] private readonly IClipboardManager _clipboard = default!;

    public event Action? Retry;

    public InterserverRedialWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CopyButton.OnPressed += _ => _clipboard.SetText(AddressLine.Text);
        RetryButton.OnPressed += _ => Retry?.Invoke();
    }

    public void SetTransfer(string address, string serverName)
    {
        AddressLine.Text = address;
        InfoLabel.Text = Loc.GetString("interserver-redial-text", ("server", serverName));
    }
}
