using System.Linq;
using Content.Shared._Lua.Interserver;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.Interserver;

[GenerateTypedNameReferences]
public sealed partial class LongRangeBssScreen : BoxContainer
{
    private List<InterserverServerInfo> _servers = new();
    private InterserverServerInfo? _selectedServer;
    private InterserverMapInfo? _selectedMap;

    public event Action? RequestRefresh;
    public event Action<string, string>? RequestTransfer;

    public LongRangeBssScreen()
    {
        RobustXamlLoader.Load(this);
        ServerSelector.OnItemSelected += args =>
        {
            ServerSelector.SelectId(args.Id);
            SelectServer(args.Id);
        };
        MapSelector.OnItemSelected += args =>
        {
            MapSelector.SelectId(args.Id);
            _selectedMap = _selectedServer?.Maps.ElementAtOrDefault(args.Id);
            UpdateButton();
        };
        RefreshButton.OnPressed += _ => RequestRefresh?.Invoke();
        TransferButton.OnPressed += _ =>
        {
            if (_selectedServer != null && _selectedMap != null)
                RequestTransfer?.Invoke(_selectedServer.Id, _selectedMap.Id);
        };
    }

    public void UpdateState(InterserverConsoleState state)
    {
        var selectedServerId = _selectedServer?.Id;
        var selectedMapId = _selectedMap?.Id;
        _servers = state.Servers;
        ServerSelector.Clear();
        for (var i = 0; i < _servers.Count; i++)
        {
            var server = _servers[i];
            ServerSelector.AddItem(server.Online ? server.Name : $"{server.Name} (offline)", i);
        }

        var serverIndex = selectedServerId == null
            ? (_servers.Count > 0 ? 0 : -1)
            : _servers.FindIndex(x => x.Id == selectedServerId);
        if (serverIndex < 0 && _servers.Count > 0)
            serverIndex = 0;
        if (serverIndex >= 0)
        {
            ServerSelector.SelectId(serverIndex);
            SelectServer(serverIndex, selectedMapId);
        }
        else
        {
            _selectedServer = null;
            _selectedMap = null;
            MapSelector.Clear();
        }

        StatusLabel.Text = state.Stage == InterserverTransferStage.Idle
            ? (_servers.Count == 0 ? Loc.GetString("long-range-bss-no-servers") : string.Empty)
            : Loc.GetString("long-range-bss-stage", ("stage", StageName(state.Stage)), ("status", state.Status));
        var busy = state.Stage is not (InterserverTransferStage.Idle or InterserverTransferStage.Failed or
            InterserverTransferStage.Completed);
        ServerSelector.Disabled = busy;
        MapSelector.Disabled = busy;
        RefreshButton.Disabled = busy;
        UpdateButton(busy);
    }

    private void SelectServer(int index, string? selectedMapId = null)
    {
        _selectedServer = _servers.ElementAtOrDefault(index);
        _selectedMap = null;
        MapSelector.Clear();
        if (_selectedServer == null)
        {
            UpdateButton();
            return;
        }
        for (var i = 0; i < _selectedServer.Maps.Count; i++)
            MapSelector.AddItem(_selectedServer.Maps[i].Name, i);
        var mapIndex = selectedMapId == null ? 0 : _selectedServer.Maps.FindIndex(x => x.Id == selectedMapId);
        if (mapIndex < 0 && _selectedServer.Maps.Count > 0)
            mapIndex = 0;
        if (mapIndex >= 0)
        {
            MapSelector.SelectId(mapIndex);
            _selectedMap = _selectedServer.Maps[mapIndex];
        }
        UpdateButton();
    }

    private void UpdateButton(bool busy = false)
    {
        TransferButton.Disabled = busy || _selectedServer is not { Online: true } || _selectedMap == null;
    }

    private static string StageName(InterserverTransferStage stage) => Loc.GetString($"long-range-bss-stage-{stage}");
}
