- type: startingGear
  id: SupremeCommander
  equipment:
    head: ClothingHeadCapSupremeCommander
    jumpsuit: ADTClothingUniformSupremeCommanderJumpsuit
    shoes: ADTClothingHandsSupremeCommanderBoots
    gloves: ADTClothingHandsSupremeCommanderGloves
    eyes: ADTClothingEyesSupremeCommanderGlass
    belt: ADTClothingBeltSupremeCommanderSheath
    neck: ADTClothingNeckSupremeCommanderCloak
    id: UniversalIDCard
    ears: ClothingHeadsetAltCentCom
#    mask: ClothingMaskNeckGaiter
    underwearb: ClothingUnderwearBottomBoxersDeathSquad
    outerClothing: ADTClothingOuterClothingSupreneCommanderArmor
    back: ClothingDeathSquadronBackpack
  inhand:
   - PonderingOrb
   - SupremeCommanderSabre
  storage:
    back:
    - WeaponDisablerIdan
    - BoxFolderCentComClipboard
    - PenCentcom
    - AccessConfiguratorUniversal
    - EmagUnlimited
    - DemagUnlimited
