- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  setPreference: false # Frontier
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1800 #0.5 hr
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: ProfessionalChef #Nyano - End Summary.

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff

# Interview variant
- type: job
  id: ChefInterview
  name: job-name-Chef-interview
  description: job-description-chef
  playTimeTracker: JobChefInterview
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 600
  setPreference: false
  startingGear: ChefHologramGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hire
  accessGroups:
  - GeneralAccess
  jobEntity: InterviewHologramChef
  newPlayerMessage: false

- type: startingGear
  id: ChefHologramGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    shoes: ClothingShoesBootsMercenary

- type: chameleonOutfit
  id: ChefChameleonOutfit
  job: Chef
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef
