using System.Linq;
using Content.Client.Administration.Systems;
using Content.Shared.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class InterserverTab : Control
{
    [Dependency] private readonly IEntitySystemManager _systems = default!;
    private readonly InterserverAdminSystem _system;
    private List<InterserverAdminPeerInfo> _peers = new();

    public InterserverTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _system = _systems.GetEntitySystem<InterserverAdminSystem>();
        _system.StateUpdated += UpdateState;
        ApplyLocalButton.OnPressed += _ => _system.ApplyLocal(Enabled.Pressed, ServerId.Text.Trim(),
            DisplayName.Text.Trim(), PublicAddress.Text.Trim());
        SavePeerButton.OnPressed += _ => _system.UpsertPeer(PeerId.Text.Trim(), PeerName.Text.Trim(),
            ApiUrl.Text.Trim(), PeerPublicAddress.Text.Trim(), SharedSecret.Text.Trim(), Approved.Pressed,
            AllowedMaps.Text.Trim());
        RemovePeerButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(PeerId.Text)) _system.RemovePeer(PeerId.Text.Trim());
        };
        TestPeerButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(PeerId.Text)) _system.TestPeer(PeerId.Text.Trim());
        };
        RefreshButton.OnPressed += _ => RequestState();
        NewPeerButton.OnPressed += _ => ClearPeer();
        PeerSelector.OnItemSelected += args =>
        {
            PeerSelector.SelectId(args.Id);
            ShowPeer(args.Id);
        };
    }

    public void RequestState() => _system.RequestState();

    private void UpdateState(InterserverAdminStateEvent state)
    {
        Enabled.Pressed = state.Enabled;
        ServerId.Text = state.ServerId;
        DisplayName.Text = state.DisplayName;
        PublicAddress.Text = state.PublicAddress;
        LocalMapsLabel.Text = Loc.GetString("admin-ui-interserver-local-maps", ("maps", state.LocalMaps));
        FeedbackLabel.Text = state.Feedback;
        var selected = PeerId.Text;
        _peers = state.Peers;
        PeerSelector.Clear();
        for (var i = 0; i < _peers.Count; i++)
            PeerSelector.AddItem(_peers[i].Approved ? _peers[i].Id : $"{_peers[i].Id} (pending)", i);
        var index = _peers.FindIndex(x => x.Id == selected);
        if (index < 0 && _peers.Count > 0) index = 0;
        if (index >= 0)
        {
            PeerSelector.SelectId(index);
            ShowPeer(index);
        }
        else ClearPeer();
    }

    private void ShowPeer(int index)
    {
        var peer = _peers.ElementAtOrDefault(index);
        if (peer == null) return;
        PeerId.Text = peer.Id;
        PeerName.Text = peer.DisplayName;
        ApiUrl.Text = peer.ApiUrl;
        PeerPublicAddress.Text = peer.PublicAddress;
        SharedSecret.Text = string.Empty;
        SharedSecret.PlaceHolder = peer.SecretConfigured
            ? Loc.GetString("admin-ui-interserver-secret-configured")
            : string.Empty;
        AllowedMaps.Text = peer.AllowedMaps;
        Approved.Pressed = peer.Approved;
    }

    private void ClearPeer()
    {
        PeerId.Text = string.Empty;
        PeerName.Text = string.Empty;
        ApiUrl.Text = string.Empty;
        PeerPublicAddress.Text = string.Empty;
        SharedSecret.Text = string.Empty;
        SharedSecret.PlaceHolder = string.Empty;
        AllowedMaps.Text = string.Empty;
        Approved.Pressed = false;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing) _system.StateUpdated -= UpdateState;
        base.Dispose(disposing);
    }
}
