using Content.Client.Administration.Systems;
using Content.Shared.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class PersistenceTab : Control
{
    [Dependency] private readonly IEntitySystemManager _entitySystems = default!;

    private readonly PersistenceAdminSystem _system;

    public PersistenceTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entitySystems.GetEntitySystem<PersistenceAdminSystem>();
        _system.StateUpdated += UpdateState;

        AutosaveInterval.IsValid = value => value is >= 1 and <= 10080;
        AutosaveInterval.InitDefaultButtons();

        ApplyButton.OnPressed += _ => _system.ApplySettings(
            PersistenceEnabled.Pressed,
            AutosaveEnabled.Pressed,
            AutosaveInterval.Value,
            SavePath.Text.Trim());
        RefreshButton.OnPressed += _ => RequestState();
        SaveNowButton.OnPressed += _ => _system.SaveNow();
    }

    public void RequestState()
    {
        _system.RequestState();
    }

    private void UpdateState(PersistenceAdminStateEvent state)
    {
        PersistenceEnabled.Pressed = state.UsePersistence;
        AutosaveEnabled.Pressed = state.AutosaveEnabled;
        AutosaveInterval.OverrideValue(state.AutosaveIntervalMinutes);
        SavePath.Text = state.SavePath;

        StatusLabel.Text = Loc.GetString(state.RoundRunning
            ? "admin-ui-persistence-status-running"
            : "admin-ui-persistence-status-lobby");
        SaveFileLabel.Text = Loc.GetString(state.SaveFileExists
            ? "admin-ui-persistence-file-exists"
            : "admin-ui-persistence-file-missing");

        NextSaveLabel.Text = state.SecondsUntilAutosave >= 0
            ? Loc.GetString("admin-ui-persistence-next-save",
                ("minutes", (int) Math.Ceiling(state.SecondsUntilAutosave / 60d)))
            : Loc.GetString("admin-ui-persistence-next-save-disabled");

        LastSaveLabel.Text = state.LastSaveUnixTime > 0
            ? Loc.GetString("admin-ui-persistence-last-save",
                ("time", DateTimeOffset.FromUnixTimeSeconds(state.LastSaveUnixTime).ToLocalTime().ToString("G")))
            : Loc.GetString("admin-ui-persistence-last-save-never");

        SaveNowButton.Disabled = !state.UsePersistence || !state.RoundRunning;
        FeedbackLabel.Text = FeedbackLoc(state.Feedback);
        FeedbackLabel.ModulateSelfOverride = state.Feedback is
            PersistenceAdminFeedback.SaveFailed or
            PersistenceAdminFeedback.InvalidPath or
            PersistenceAdminFeedback.InvalidInterval or
            PersistenceAdminFeedback.NotInRound or
            PersistenceAdminFeedback.PersistenceDisabled or
            PersistenceAdminFeedback.FtlInProgress
                ? Color.Red
                : null;
    }

    private static string FeedbackLoc(PersistenceAdminFeedback feedback)
    {
        if (feedback == PersistenceAdminFeedback.None)
            return string.Empty;

        return Loc.GetString(feedback switch
        {
            PersistenceAdminFeedback.SettingsApplied => "admin-ui-persistence-feedback-applied",
            PersistenceAdminFeedback.SaveSucceeded => "admin-ui-persistence-feedback-save-succeeded",
            PersistenceAdminFeedback.SaveFailed => "admin-ui-persistence-feedback-save-failed",
            PersistenceAdminFeedback.InvalidPath => "admin-ui-persistence-feedback-invalid-path",
            PersistenceAdminFeedback.InvalidInterval => "admin-ui-persistence-feedback-invalid-interval",
            PersistenceAdminFeedback.NotInRound => "admin-ui-persistence-feedback-not-in-round",
            PersistenceAdminFeedback.PersistenceDisabled => "admin-ui-persistence-feedback-disabled",
            PersistenceAdminFeedback.FtlInProgress => "admin-ui-persistence-feedback-ftl",
            _ => "admin-ui-persistence-feedback-save-failed",
        });
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _system.StateUpdated -= UpdateState;

        base.Dispose(disposing);
    }
}
