# Mech Weapons
- type: latheRecipe
  id: WeaponMechCombatImmolationGun
  result: WeaponMechCombatImmolationGun
  completetime: 10
  materials:
    Steel: 2800
    Plastic: 1000
    Plasma: 750
    Glass: 500
    Silver: 150

- type: latheRecipe
  id: WeaponMechCombatSolarisLaser
  result: WeaponMechCombatSolarisLaser
  completetime: 10
  materials:
    Steel: 1650
    Plastic: 300
    Plasma: 250
    Glass: 400
    Silver: 150

- type: latheRecipe
  id: WeaponMechCombatFiredartLaser
  result: WeaponMechCombatFiredartLaser
  completetime: 10
  materials:
    Steel: 1200
    Plastic: 200
    Plasma: 150
    Glass: 250
    Silver: 100

- type: latheRecipe
  id: WeaponMechCombatUltraRifle
  result: WeaponMechCombatUltraRifle
  completetime: 10
  materials:
    Steel: 1000
    Plasteel: 250
    Plastic: 200
    Silver: 100

- type: latheRecipe
  id: WeaponMechCombatShotgun
  result: WeaponMechCombatShotgun
  completetime: 10
  materials:
    Steel: 1600
    Plasteel: 200
    Plastic: 550
    Silver: 100

- type: latheRecipe
  id: WeaponMechCombatShotgunIncendiary
  result: WeaponMechCombatShotgunIncendiary
  completetime: 10
  materials:
    Steel: 1500
    Plasteel: 200
    Plastic: 700
    Plasma: 300
    Silver: 100

- type: latheRecipe
  id: WeaponMechCombatDisabler
  result: WeaponMechCombatDisabler
  completetime: 10
  materials:
    Steel: 750
    Plasteel: 100
    Glass: 250
    Plastic: 300
    Silver: 50

- type: latheRecipe
  id: WeaponMechCombatFlashbangLauncher
  result: WeaponMechCombatFlashbangLauncher
  completetime: 10
  materials:
    Steel: 1200
    Plasteel: 100
    Glass: 300
    Plastic: 450
    Silver: 100

- type: latheRecipe
  id: WeaponMechCombatMissileRack6
  result: WeaponMechCombatMissileRack6
  completetime: 10
  materials:
    Steel: 2500
    Glass: 1500
    Plastic: 700
    Silver: 100

- type: latheRecipe
  id: WeaponMechCombatMissileRack8
  result: WeaponMechCombatMissileRack8
  completetime: 11
  materials:
    Steel: 2250
    Plasteel: 450
    Glass: 1500
    Plastic: 500
    Silver: 150

- type: latheRecipe
  id: MechEquipmentKineticAccelerator
  result: WeaponMechIndustrialKineticAccelerator
  completetime: 10
  materials:
    Steel: 1500
    Plasteel: 100
    Glass: 750
    Silver: 150

- type: latheRecipe
  id: MechEquipmentChainSword
  result: WeaponMechChainSword
  completetime: 15
  materials:
    Steel: 1200
    Plasteel: 750
    Silver: 600
    Diamond: 50
