// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Shared._Lua.Shipyard.BUI;
using Content.Shared._NF.Bank;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;

namespace Content.Client._Lua.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ParkingConsoleMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    public event Action<BaseButton.ButtonEventArgs>? OnPark;
    public event Action<BaseButton.ButtonEventArgs>? OnRecall;
    public event Action<BaseButton.ButtonEventArgs>? OnExtendParking;
    public event Action<NetEntity?>? OnDockPortSelected;
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly SharedTransformSystem _xform;
    private NavInterfaceState? _dockNav;
    private NetEntity? _selectedDockPort;
    private bool _hasDeed;
    private bool _isParked;
    private bool _canExtendParking;
    private TimeSpan _parkingRemainingEnd;
    private TimeSpan _cooldownEnd;

    public ParkingConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xform = _entManager.System<SharedTransformSystem>();
        Title = Loc.GetString("shipyard-console-menu-title-parking");
        ParkButton.OnPressed += args => OnPark?.Invoke(args);
        RecallButton.OnPressed += args => OnRecall?.Invoke(args);
        ExtendParkingButton.OnPressed += args => OnExtendParking?.Invoke(args);
        DockRadar.ShowIFF = false;
        DockRadar.ShowIFFShuttles = false;
        DockRadar.ShowDocks = true;
        DockRadar.OnRadarClick += OnDockRadarClick;
    }

    public void UpdateState(ParkingConsoleInterfaceState state)
    {
        _hasDeed = state.ShipDeedTitle != null;
        _isParked = state.IsShuttleParked;
        _canExtendParking = state.CanExtendParking;
        _parkingRemainingEnd = _timing.CurTime + state.ParkingRemaining;
        _cooldownEnd = _timing.CurTime + state.ActionCooldownRemaining;
        TargetIdButton.Text = state.IsTargetIdPresent ? Loc.GetString("id-card-console-window-eject-button") : Loc.GetString("id-card-console-window-insert-button");
        NoDeedHelperContainer.Visible = !state.IsTargetIdPresent;
        DeedContainer.Visible = state.IsTargetIdPresent;
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        DeedTitle.Text = state.ShipDeedTitle ?? Loc.GetString("shipyard-console-deed-label-none");
        ParkingStatus.Text = Loc.GetString(state.IsShuttleParked ? "shipyard-console-parking-status-parked" : "shipyard-console-parking-status-active");
        ParkingPrice.Text = state.ShipDeedTitle == null
            ? string.Empty
            : Loc.GetString("shipyard-console-parking-price", ("price", BankSystemExtensions.ToSpesoString(state.ParkingPrice)));
        UpdateTimedLabels();
        UpdateButtons();
    }

    public void UpdateDockSelect(NavInterfaceState? nav, NetEntity? selectedPort)
    {
        if (nav == null)
        {
            _dockNav = null;
            _selectedDockPort = null;
            UpdateButtons();
            return;
        }
        _dockNav = nav;
        _selectedDockPort = selectedPort;
        DockRadar.UpdateState(nav);
        DockRadar.HighlightDockPort = selectedPort;
        UpdateButtons();
    }

    private void UpdateButtons()
    {
        var coolingDown = GetCooldownRemaining() > TimeSpan.Zero;
        ParkButton.Disabled = !_hasDeed || _isParked || coolingDown;
        RecallButton.Disabled = !_hasDeed || !_isParked || _selectedDockPort == null || coolingDown;
        ExtendParkingButton.Disabled = !_hasDeed || !_canExtendParking || GetParkingRemaining() <= TimeSpan.Zero;
    }

    private void UpdateTimedLabels()
    {
        if (!_hasDeed)
        {
            ParkingRemaining.Text = string.Empty;
            ParkingCooldown.Visible = false;
            return;
        }

        var parkingRemaining = GetParkingRemaining();
        ParkingRemaining.Text = Loc.GetString("shipyard-console-parking-time-remaining", ("time", FormatTime(parkingRemaining)));

        var cooldownRemaining = GetCooldownRemaining();
        ParkingCooldown.Visible = cooldownRemaining > TimeSpan.Zero;
        ParkingCooldown.Text = Loc.GetString("shipyard-console-parking-cooldown", ("time", FormatTime(cooldownRemaining)));
    }

    private TimeSpan GetParkingRemaining()
    {
        var remaining = _parkingRemainingEnd - _timing.CurTime;
        return remaining > TimeSpan.Zero ? remaining : TimeSpan.Zero;
    }

    private TimeSpan GetCooldownRemaining()
    {
        var remaining = _cooldownEnd - _timing.CurTime;
        return remaining > TimeSpan.Zero ? remaining : TimeSpan.Zero;
    }

    private static string FormatTime(TimeSpan time)
    {
        if (time <= TimeSpan.Zero)
            return "00:00";

        return $"{(int)time.TotalMinutes:00}:{time.Seconds:00}";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateTimedLabels();
        UpdateButtons();
    }

    private void OnDockRadarClick(EntityCoordinates coords)
    {
        if (_dockNav == null) return;
        var clickMapPos = _xform.ToMapCoordinates(coords).Position;
        NetEntity? best = null;
        var bestDistSq = float.MaxValue;
        foreach (var (_, ports) in _dockNav.Docks)
        {
            foreach (var port in ports)
            {
                var portCoords = _entManager.GetCoordinates(port.Coordinates);
                if (!portCoords.IsValid(_entManager)) continue;
                var portMapPos = _xform.ToMapCoordinates(portCoords).Position;
                var distSq = (portMapPos - clickMapPos).LengthSquared();
                if (distSq < bestDistSq)
                {
                    bestDistSq = distSq;
                    best = port.Entity;
                }
            }
        }
        const float maxPickDistance = 4.0f;
        if (best == null || bestDistSq > maxPickDistance * maxPickDistance)
        {
            _selectedDockPort = null;
            DockRadar.HighlightDockPort = null;
            OnDockPortSelected?.Invoke(null);
            UpdateButtons();
            return;
        }
        if (_selectedDockPort.HasValue && best == _selectedDockPort.Value)
        {
            _selectedDockPort = null;
            DockRadar.HighlightDockPort = null;
            OnDockPortSelected?.Invoke(null);
            UpdateButtons();
            return;
        }
        _selectedDockPort = best;
        DockRadar.HighlightDockPort = best;
        OnDockPortSelected?.Invoke(best);
        UpdateButtons();
    }
}
