// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.FireControl;
using Content.Shared._Mono.ShipGuns;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Numerics;

namespace Content.Client._Mono.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    private const float WeaponButtonHeight = 36f;
    private const float WeaponAmmoWidth = 44f;

    [Dependency] private readonly IEntityManager _entityManager = default!;

    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;

    public readonly Dictionary<NetEntity, Button> WeaponsList = new();

    private readonly Dictionary<NetEntity, BoxContainer> _weaponRows = new();
    private readonly Dictionary<NetEntity, Label> _weaponAmmoLabels = new();
    private readonly Dictionary<NetEntity, bool> _weaponAmmoEmpty = new();
    private bool _suppressWeaponToggle;

    private List<HashSet<NetEntity>> _presets = new();
    private readonly Dictionary<int, Button> _presetButtons = new();
    private int? _selectedPresetIndex;
    private bool _suppressPresetToggle;

    // Dictionary to store weapon name to entity mapping for easier filtering
    private readonly Dictionary<string, NetEntity> _weaponNameToEntity = new();

    // Dictionary to store weapon entity to type mapping
    private readonly Dictionary<NetEntity, ShipGunType> _weaponTypes = new();

    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        ShowIFFCheckbox.OnToggled += args => NavRadar.ShowIFF = args.Pressed;
        AutoDeselectEmptyCheckbox.OnToggled += _ =>
        {
            if (ApplyAutoDeselectEmpty())
                OnWeaponSelectionChanged?.Invoke();
        };
        SelectAllButton.OnPressed += SelectAllWeapons;
        UnselectAllButton.OnPressed += UnselectAllWeapons;
        SelectBallisticButton.OnPressed += SelectBallisticWeapons;
        SelectEnergyButton.OnPressed += SelectEnergyWeapons;
        SelectMissileButton.OnPressed += SelectMissileWeapons;
        SelectMiningButton.OnPressed += SelectMiningWeapons;
        SavePresetButton.OnPressed += SavePreset;
        DeletePresetButton.OnPressed += DeleteSelectedPreset;
        UpdatePresetActionButtons();
    }

    public void SetPresetStorage(List<HashSet<NetEntity>> presets)
    {
        _presets = presets;
        RebuildPresetList();
    }

    private void SelectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        try
        {
            _suppressWeaponToggle = true;
            foreach (var button in WeaponsList.Values)
            {
                button.Pressed = true;
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void UnselectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        try
        {
            _suppressWeaponToggle = true;
            foreach (var button in WeaponsList.Values)
            {
                button.Pressed = false;
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void SelectBallisticWeapons(BaseButton.ButtonEventArgs args)
    {
        try
        {
            _suppressWeaponToggle = true;

            // First unselect all weapons
            foreach (var button in WeaponsList.Values)
            {
                button.Pressed = false;
            }

            // Then select only ballistic weapons
            foreach (var kvp in WeaponsList)
            {
                var weaponEntity = kvp.Key;
                var button = kvp.Value;

                if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Ballistic)
                {
                    button.Pressed = true;
                }
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void SelectEnergyWeapons(BaseButton.ButtonEventArgs args)
    {
        try
        {
            _suppressWeaponToggle = true;

            // First unselect all weapons
            foreach (var button in WeaponsList.Values)
            {
                button.Pressed = false;
            }

            // Then select only energy weapons
            foreach (var kvp in WeaponsList)
            {
                var weaponEntity = kvp.Key;
                var button = kvp.Value;

                if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Energy)
                {
                    button.Pressed = true;
                }
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void SelectMissileWeapons(BaseButton.ButtonEventArgs args)
    {
        try
        {
            _suppressWeaponToggle = true;

            // First unselect all weapons
            foreach (var button in WeaponsList.Values)
            {
                button.Pressed = false;
            }

            // Then select only missile weapons
            foreach (var kvp in WeaponsList)
            {
                var weaponEntity = kvp.Key;
                var button = kvp.Value;

                if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Missile)
                {
                    button.Pressed = true;
                }
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void SelectMiningWeapons(BaseButton.ButtonEventArgs args)
    {
        try
        {
            _suppressWeaponToggle = true;

            foreach (var button in WeaponsList.Values)
            {
                button.Pressed = false;
            }
            foreach (var kvp in WeaponsList)
            {
                var weaponEntity = kvp.Key;
                var button = kvp.Value;

                if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Mining)
                {
                    button.Pressed = true;
                }
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void FinishWeaponSelectionChange()
    {
        ApplyAutoDeselectEmpty();
        UpdatePresetActionButtons();
        OnWeaponSelectionChanged?.Invoke();
    }

    private bool ApplyAutoDeselectEmpty()
    {
        if (!AutoDeselectEmptyCheckbox.Pressed)
            return false;

        try
        {
            var changed = false;
            _suppressWeaponToggle = true;
            foreach (var (weapon, button) in WeaponsList)
            {
                if (!button.Pressed)
                    continue;

                if (!_weaponAmmoEmpty.TryGetValue(weapon, out var empty) || !empty)
                    continue;

                button.Pressed = false;
                changed = true;
            }

            return changed;
        }
        finally
        {
            _suppressWeaponToggle = false;
        }
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        UpdateWeaponsList(state);
        if (ApplyAutoDeselectEmpty())
            OnWeaponSelectionChanged?.Invoke();

        // Update the category buttons state based on whether weapons of that type are available
        bool hasBallisticWeapons = false;
        bool hasEnergyWeapons = false;
        bool hasMissileWeapons = false;
        bool hasMiningWeapons = false;

        foreach (var kvp in _weaponTypes)
        {
            var type = kvp.Value;

            if (type == ShipGunType.Ballistic)
                hasBallisticWeapons = true;
            else if (type == ShipGunType.Energy)
                hasEnergyWeapons = true;
            else if (type == ShipGunType.Missile)
                hasMissileWeapons = true;
            else if (type == ShipGunType.Mining)
                hasMiningWeapons = true;

            if (hasBallisticWeapons && hasEnergyWeapons && hasMissileWeapons && hasMiningWeapons)
                break;
        }

        SelectBallisticButton.Disabled = !hasBallisticWeapons;
        SelectEnergyButton.Disabled = !hasEnergyWeapons;
        SelectMissileButton.Disabled = !hasMissileWeapons;
        SelectMiningButton.Disabled = !hasMiningWeapons;
        UpdatePresetActionButtons();
    }

    private void UpdateWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        if (state.FireControllables == null)
        {
            WeaponsList.Clear();
            _weaponRows.Clear();
            _weaponAmmoLabels.Clear();
            _weaponAmmoEmpty.Clear();
            ControllablesBox.DisposeAllChildren();
            _weaponNameToEntity.Clear();
            _weaponTypes.Clear();
            PrunePresetsToAvailable();
            return;
        }

        var toRemove = new HashSet<NetEntity>(WeaponsList.Keys);
        _weaponNameToEntity.Clear();
        _weaponTypes.Clear();

        foreach (var controllable in state.FireControllables)
        {
            // Store the weapon name and entity for filtering
            _weaponNameToEntity[controllable.Name] = controllable.NetEntity;
            _weaponAmmoEmpty[controllable.NetEntity] = controllable.AmmoEmpty;

            // Store the weapon type if available
            var entity = _entityManager.GetEntity(controllable.NetEntity);
            if (_entityManager.TryGetComponent<ShipGunTypeComponent>(entity, out var typeComp))
            {
                _weaponTypes[controllable.NetEntity] = typeComp.Type;
            }

            if (WeaponsList.TryGetValue(controllable.NetEntity, out var existingButton))
            {
                toRemove.Remove(controllable.NetEntity);
                existingButton.Text = controllable.Name;
                UpdateAmmoLabel(controllable);
            }
            else
            {
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    MinHeight = WeaponButtonHeight,
                    MaxHeight = WeaponButtonHeight,
                    Margin = new Thickness(4, 1)
                };

                var ammoPanel = new PanelContainer
                {
                    MinSize = new Vector2(WeaponAmmoWidth, WeaponButtonHeight),
                    MaxSize = new Vector2(WeaponAmmoWidth, WeaponButtonHeight),
                    Margin = new Thickness(0, 0, 4, 0),
                    PanelOverride = new StyleBoxFlat
                    {
                        BorderThickness = new Thickness(2),
                        BorderColor = Color.FromHex("#2e2e2e"),
                        BackgroundColor = Color.FromHex("#1c1c1c")
                    }
                };

                var ammoLabel = new Label
                {
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    Align = Label.AlignMode.Center
                };

                ammoPanel.AddChild(ammoLabel);
                row.AddChild(ammoPanel);

                var button = new Button
                {
                    ToggleMode = true,
                    Text = controllable.Name,
                    StyleClasses = { "ButtonSquare OpenRight" },
                    HorizontalExpand = true,
                    SetHeight = WeaponButtonHeight,
                };

                button.OnToggled += _ =>
                {
                    if (!_suppressWeaponToggle)
                        FinishWeaponSelectionChange();
                };

                row.AddChild(button);
                ControllablesBox.AddChild(row);
                WeaponsList.Add(controllable.NetEntity, button);
                _weaponRows.Add(controllable.NetEntity, row);
                _weaponAmmoLabels.Add(controllable.NetEntity, ammoLabel);
                UpdateAmmoLabel(controllable);
            }
        }

        foreach (var entity in toRemove)
        {
            if (_weaponRows.TryGetValue(entity, out var row))
            {
                ControllablesBox.RemoveChild(row);
            }

            WeaponsList.Remove(entity);
            _weaponRows.Remove(entity);
            _weaponAmmoLabels.Remove(entity);
            _weaponAmmoEmpty.Remove(entity);
        }

        SelectAllButton.Disabled = WeaponsList.Count == 0;
        UnselectAllButton.Disabled = WeaponsList.Count == 0;
        PrunePresetsToAvailable();
        UpdatePresetActionButtons();
    }

    private void UpdateAmmoLabel(FireControllableEntry controllable)
    {
        if (!_weaponAmmoLabels.TryGetValue(controllable.NetEntity, out var label))
            return;

        label.Text = string.IsNullOrWhiteSpace(controllable.AmmoStatus)
            ? "-"
            : controllable.AmmoStatus;
        label.FontColorOverride = controllable.AmmoEmpty
            ? Color.OrangeRed
            : Color.LightGreen;
    }

    private HashSet<NetEntity> GetSelectedWeapons()
    {
        var selected = new HashSet<NetEntity>();
        foreach (var (weapon, button) in WeaponsList)
        {
            if (button.Pressed)
                selected.Add(weapon);
        }

        return selected;
    }

    private void SelectOnlyWeapons(HashSet<NetEntity> weapons)
    {
        try
        {
            _suppressWeaponToggle = true;
            foreach (var (weapon, button) in WeaponsList)
            {
                button.Pressed = weapons.Contains(weapon);
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void DeselectPresetWeapons(HashSet<NetEntity> weapons)
    {
        try
        {
            _suppressWeaponToggle = true;
            foreach (var weapon in weapons)
            {
                if (WeaponsList.TryGetValue(weapon, out var button))
                    button.Pressed = false;
            }
        }
        finally
        {
            _suppressWeaponToggle = false;
        }

        FinishWeaponSelectionChange();
    }

    private void SavePreset(BaseButton.ButtonEventArgs args)
    {
        var selected = GetSelectedWeapons();
        if (selected.Count == 0)
            return;

        if (_selectedPresetIndex is { } index && index >= 0 && index < _presets.Count)
        {
            _presets[index] = selected;
        }
        else
        {
            _presets.Add(selected);
            _selectedPresetIndex = _presets.Count - 1;
        }

        RebuildPresetList();
        SetSelectedPresetButton(_selectedPresetIndex);
        UpdatePresetActionButtons();
    }

    private void DeleteSelectedPreset(BaseButton.ButtonEventArgs args)
    {
        if (_selectedPresetIndex is not { } index || index < 0 || index >= _presets.Count)
            return;

        _presets.RemoveAt(index);
        _selectedPresetIndex = null;
        RebuildPresetList();
        UpdatePresetActionButtons();
    }

    private void PressPreset(int index)
    {
        if (index < 0 || index >= _presets.Count)
            return;

        var availablePresetWeapons = GetAvailablePresetWeapons(_presets[index]);
        if (availablePresetWeapons.Count == 0)
            return;

        if (_selectedPresetIndex == index)
        {
            DeselectPresetWeapons(availablePresetWeapons);
            _selectedPresetIndex = null;
            SetSelectedPresetButton(null);
        }
        else
        {
            _selectedPresetIndex = index;
            SelectOnlyWeapons(availablePresetWeapons);
            SetSelectedPresetButton(index);
        }

        UpdatePresetActionButtons();
    }

    private HashSet<NetEntity> GetAvailablePresetWeapons(HashSet<NetEntity> preset)
    {
        var available = new HashSet<NetEntity>();
        foreach (var weapon in preset)
        {
            if (WeaponsList.ContainsKey(weapon))
                available.Add(weapon);
        }

        return available;
    }

    private void PrunePresetsToAvailable()
    {
        var changed = false;
        for (var i = _presets.Count - 1; i >= 0; i--)
        {
            if (_presets[i].RemoveWhere(weapon => !WeaponsList.ContainsKey(weapon)) > 0)
                changed = true;

            if (_presets[i].Count == 0)
            {
                _presets.RemoveAt(i);
                changed = true;

                if (_selectedPresetIndex == i)
                    _selectedPresetIndex = null;
                else if (_selectedPresetIndex > i)
                    _selectedPresetIndex--;
            }
        }

        if (changed)
            RebuildPresetList();
    }

    private void RebuildPresetList()
    {
        PresetsBox.DisposeAllChildren();
        _presetButtons.Clear();

        for (var i = 0; i < _presets.Count; i++)
        {
            var index = i;
            var button = new Button
            {
                ToggleMode = true,
                Text = Loc.GetString("gunnery-preset-name", ("number", i + 1)),
                StyleClasses = { "ButtonSquare OpenRight" },
                HorizontalExpand = true,
                SetHeight = WeaponButtonHeight,
                Margin = new Thickness(4, 1)
            };

            button.OnToggled += _ =>
            {
                if (!_suppressPresetToggle)
                    PressPreset(index);
            };

            PresetsBox.AddChild(button);
            _presetButtons[index] = button;
        }

        if (_selectedPresetIndex >= _presets.Count)
            _selectedPresetIndex = null;

        SetSelectedPresetButton(_selectedPresetIndex);
        UpdatePresetActionButtons();
    }

    private void SetSelectedPresetButton(int? selectedIndex)
    {
        try
        {
            _suppressPresetToggle = true;
            foreach (var (index, button) in _presetButtons)
            {
                button.Pressed = selectedIndex == index;
            }
        }
        finally
        {
            _suppressPresetToggle = false;
        }
    }

    private void UpdatePresetActionButtons()
    {
        SavePresetButton.Disabled = GetSelectedWeapons().Count == 0;
        DeletePresetButton.Disabled = _selectedPresetIndex is not { } index || index < 0 || index >= _presets.Count;
    }
}
